[package]
name = "mmids-app"
version = "0.1.0"
edition = "2018"

[dependencies]
mmids-core = {path = "../mmids-core"}
tokio = { version = "1.12", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3.2"
tracing-futures = "0.2.5"