[package]
name = "ffmpeg-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
mmids-core = {path = "../../mmids-core"}
tokio = { version = "1.12", features = ["full"] }
env_logger = "0.9.0"
log = "0.4"
uuid = { version = "0.8", features = ["v4"] }
